# WARNING: THIS FILE IS MANAGED IN THE 'BOILERPLATE' REPO AND COPIED TO OTHER REPOSITORIES.
# ONLY EDIT THIS FILE FROM WITHIN THE 'FLYTEORG/BOILERPLATE' REPOSITORY:
#
# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst

version: "2"

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    paths:
      - pkg/client
    rules:
      - text: deprecated

formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/flyteorg)
