version: "2"

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - protogetter
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    paths:
      - pkg/client
      - gen
    rules:
      - text: deprecated

formatters:
  enable:
    - goimports
