version: "2"

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - protogetter
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      ignore-tests: true
  exclusions:
    paths:
      - pkg/client
    rules:
      - text: copylocks
      - text: deprecated

formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/flyteorg)
