version: "2"

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - protogetter
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      ignore-tests: true
  exclusions:
    paths:
      - cmd/entrypoints/serve.go
      - pkg/async/messages/sqs.go
    rules:
      - path: pkg/workflowengine/impl/prepare_execution.go
        text: "copies lock"
      - path: pkg/runtime/interfaces/application_configuration.go
        text: "G402: TLS InsecureSkipVerify may be true."
      - text: deprecated

formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/flyteorg)
